### ISSUE TITLE
save image in canvas

### ISSUE THREAD

**Issue by patatetom** [timdream/wordcloud2.js#100]
hi,
is there an other way to run wordcloud2.js ? (for just get the image, to not have to open the html file in the browser and save the image)
and how could I feed the list of words from an external file ?
very good work !
regards, lacsaP.

**Comment by timdream** [comment]
You might be able to run WordCloud in a headless browser or even JSDom. It is designed to work in a browser and it's really not hard to get it...

**Comment by patatetom** [comment]
thanks for the tracks :-)
regards, lacsaP.

**Comment by patatetom** [comment]
https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md
and what about list of words from an external file ?

**Comment by timdream** [comment]
> https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md
> and what about list of words from an external file ?

@patatetom It would depend on how you want to control your headless instances. You could use frameworks like WebDriver but a simple shell script simply works. It shouldn't be hard to have your JavaScript in the HTML to fetch a file or passing a JS array from the framework to the browser context.
