### ISSUE TITLE
rotateRatio: callback function. First word always horizontal?

### ISSUE THREAD

**Issue by Pyot** [timdream/wordcloud2.js#102]
I would like to keep rotateRatio: for first element "0".
I try to use to call back function:

  rotateRatio: function (fontSize) {
                    if (fontSize === 50 ) {
                      return 0;
                  } else {
                      return 0.5;
                  }
              },

But it dosen't sems to work.
Can I use call back function on rotateRatio?
If not any idea how to make the first word always horizontal?

**Comment by timdream** [comment]
Thanks for filing. It would be a feature someone has to implement. It currently does not detect whether or not `rotateRatio` is a function.

https://github.com/timdream/wordcloud2.js/blob/cb447f15a7a4df996a3e18625a5c80e45f85c06d/src/wordcloud2.js#L473-L479

**Comment by timdream** [comment]
Cleaning up the issue since this is mentioned on the [roadmap](https://github.com/timdream/wordcloud2.js/blob/263f3abaf785f307f068f6d9a1438c3b94993e9a/CONTRIBUTING.md#more-api-features).
