### ISSUE TITLE
Text does not resize depending on width of container. 

### ISSUE THREAD

**Issue by mjkokotas** [timdream/wordcloud2.js#105]
Hi there,

I'm using this in conjunction with Angular 2. Most things are great (probably the best plugin for word clouds!).
This may be my lack of knowledge, but I am unable to get the text weight to resizes depending on the container size. Currently, every time the container resizes I lose words within the cloud instead of the weight reducing. Do you have a work around for this?

` this.wordService.GetWordsCount(text).then( (list) => {

            let scale = list.map((ww) => new WordWeight(ww.word, Math.pow(ww.count,2)));

            let max = scale.map((ww) => ww.count).
                reduce((max, cur) => {
                    return Math.max(max, cur);
                }, 0);

            scale = scale.map((ww) => new WordWeight(ww.word, (ww.count / max) * this.maxSize));

            let outarray = scale.map((ww) => [ww.word, ww.count]);

            console.log(outarray);

            WordCloud(document.getElementById("my_canvas"), {

                list: outarray,
                gridSize: 1,
                minSize: 0,
                click: function(item) {
                    alert(item[0] + ': ' + item[1]);
                  },
                // backgroundColor: '#333300',
                // color: function (word, weight) { return '#000000' }
                
            });

        }); `

Really appreciate any help with this!

Mason

**Comment by timdream** [comment]
WordCloud does not reduce the font size as the canvas size changes. You must estimate a `weightFactor` and set it according to your estimation. I assume it should have a better API to reduce the confusion here.

**Comment by timdream** [comment]
Cleaning up since this is mentioned on the [roadmap](https://github.com/timdream/wordcloud2.js/blob/263f3abaf785f307f068f6d9a1438c3b94993e9a/CONTRIBUTING.md#virtual-canvas-never-miss-a-word-thats-too-big-and-forget-about-weightfactor).

**Comment by ghost** [comment]
@mjkokotas Hi, how have you got this working with Angular 2. Please can you let me know.

**Comment by mjkokotas** [comment]
I was working on it but the project that I was working on is now with
someone else when I left the company... sorry!!!

**Comment by ghost** [comment]
@mjkokotas Theres no way for you to see the source code? Im kind of stuck at the moment with this.

**Comment by mjkokotas** [comment]
Unfortunately no, I've been locked out of all projects & I'm not sure if
they even finished that part.

I was stuck myself, so I just left it for later as it wasn't important.
Hope you work it out! good luck!
