### ISSUE TITLE
Hover tooltip

### ISSUE THREAD

**Issue by kidjykit** [timdream/wordcloud2.js#106]

**Comment by kidjykit** [comment]
{
  gridSize: 18,
  weightFactor: 3,
  fontFamily: 'Finger Paint, cursive, sans-serif',
  color: '#f0f0c0',
  hover: window.drawBox,
  click: function(item) {
    alert(item[0] + ': ' + item[1]);
  },
  backgroundColor: '#001f00'
}

How to change alert to hover tooltip?

**Comment by timdream** [comment]
tooltip and `drawBox` is not part of the library. Please refer to the implementation in the page.

**Comment by kidjykit** [comment]
Sry, i mean i can't change option click alert(item) to hover tooltip item on canvas. I don't know how to change its. Suggest me pls. Thank you very much.
