### ISSUE TITLE
react integration

### ISSUE THREAD

**Issue by sghgh1996** [timdream/wordcloud2.js#108]
I am developing a react application and I want to use this library in that. Can any body help me about that.?

**Comment by ajhool** [comment]
Timdream has an npm module available that you can add to your react application using:

`yarn add wordcloud`
or
`npm install --save wordcloud`

Then, the goal is to have a canvas element in your render method -- once the component is mounted, you will populate your canvas element with Wordcloud. You can use ref and this.refs to access your canvas dom element. Example component:

```
import Wordcloud from 'wordcloud';
import React, { Component } from 'react';

const SimpleWordcloud extends Component {

  onComponentMount() {
    const list = [["foo", 5], ["bar", 3]];
    Wordcloud(
      this.refs["my-canvas"],
      {list: list}
    );
  }

  render() {
    return (<div>
      <canvas ref="my-canvas" />
    </div>)
  }
}
```

Chances are that you might want to store the list in the state, so this pattern doesn't really follow best practices -- but it should give you an idea of how to load the wordcloud into the canvas using refs.

**Comment by sghgh1996** [comment]
Thank you much @ajhool . That's true. I used it and it helped me.

**Comment by timdream** [comment]
@ajhool Thanks for helping out. I, however, don't think the React component will respond to any state change, right? Such usage is probably not somewhere that React shines... 

Closing as it is unrelated to the library itself.

**Comment by dandv** [comment]
@Tarabyte published https://github.com/Tarabyte/react-wordcloud2. No documentation though.
