### ISSUE TITLE
How to avoid very small words inside big letters

### ISSUE THREAD

**Issue by t0pZ** [timdream/wordcloud2.js#110]
Hi Tim!

May I know if there is any way we can put very small words outside big letters when we have the biggest at the center? I have attached a sample.  'Fussy' and 'Open' is inside O, 'Fin Re' within 'e' and 'Big' that is within 'v' - all in the word innovative.  I know we can use 'gridsize', but i would like to just retain the spacing of the words outside 'innovative'.  Thank you!

![image](https://user-images.githubusercontent.com/22494680/31492182-9378a3d6-af7c-11e7-9c49-777380ce2e30.png)

**Comment by timdream** [comment]
It's definitely possible to modify the code to make it exclude the area. I don't have time currently to get to it though.

**Comment by t0pZ** [comment]
Thank you Tim for your positive reply about this back then. 

I could try to take a look at how to modify the code.  However, would you be able to advice, even on a very high level, a logic that I could follow for this and which part(s) of the code, please (e.g. probably somehow i should be able to get all pixel values inside the 'box area' of a word so that they are 'included' in the 'occupied array' for the positioning other words)? and should i focus on the code referring to "// Read the pixels and save the information to the occupied array"?

**Comment by timdream** [comment]
> should i focus on the code referring to "// Read the pixels and save the information to the occupied array"?

@t0wffeevessy Yes, that's the right place to modify. To make life easier you can actually append the canvas being measured to the body to see what's being drawn. 

I however don't think it make sense to implement features until we make the library pluggable. See [roadmap](https://github.com/timdream/wordcloud2.js/blob/263f3abaf785f307f068f6d9a1438c3b94993e9a/CONTRIBUTING.md#more-api-features). You are very welcome to implement this on your own fork for now.

**Comment by PrimozGodec** [comment]
@t0wffeevessy did you succeed to put small words out of the big letters?
