### ISSUE TITLE
Shape option has no effect and the default is a rectangle

### ISSUE THREAD

**Issue by ajhool** [timdream/wordcloud2.js#114]
Failure: shape option does not change the layout. Default is also a rectangle and not a circle, which suggests that the shape function is not executing properly.

Browser/Platform: Chrome, Firefox on Mac, Android (did not test others).

Code Versions: Tested on the demo page, the npm module, and a directly cloned repo.

Recent commits do not appear to have altered the code and I am new to the project so I am not sure when this was working last.

**Comment by timdream** [comment]
Could you paste the code executed?

**Comment by timdream** [comment]
Close due to inactivity.
