### ISSUE TITLE
Help! I don't know how to implement this utilizing Ionic...

### ISSUE THREAD

**Issue by estherrios2** [timdream/wordcloud2.js#115]
**Hi! I already added the WordCloud module to my project. Yet, I face a lot of problems when trying to at least show the simplest word cloud. I don't know what I'm doing wrong...**

**home.ts code:****

```
    import { Component } from '@angular/core';

    import { NavController } from 'ionic-angular';

    import { WordCloud } from 'wordcloud';

    @Component({
      selector: 'page-home',
      templateUrl: 'home.html'
    })
    export class HomePage {

      list = [['foo', 12], ['bar', 6]];

      constructor(public navCtrl: NavController) {
      }

      WordCloud(document.getElementById('my_canvas'), { list: list } );

    }

```
**home.html code:**

```
    <ion-header>
      <ion-navbar>
        <ion-title>
          Ionic Blank
        </ion-title>
      </ion-navbar>
    </ion-header>

    <ion-content padding>
      <canvas id="my_canvas"></canvas>
    </ion-content>
```

**HELP PLEASE && THANK YOU**

**Comment by smallbitt** [comment]
How did you add this module to your project? is there typings for this script?
if not you should import the script in index.html file and then declare the global variable before use it in the ts.

**Comment by smallbitt** [comment]
I figured out how to make it work on ionic2 or ionic3.

## Installation:
`npm install wordcloud --save`
`npm install @types/wordcloud --save`

## Implementation:
First of all, don't use this:
`import { WordCloud } from 'wordcloud';"`
but use this: 
`import * as WordCloud from 'wordcloud';`
then add a property in the class like you already did:
 ` list = [['foo', 25], ['bar', 36]];`
and in the constructor:
not: 
`  WordCloud(document.getElementById('canvas'), { list: list } );`
but instead:
`  WordCloud(document.getElementById('canvas'), { list: this.list } );`

now last thing is in html file add the canvas:
`<canvas id="canvas" class="canvas"></canvas>`

hope it helps.

**Comment by timdream** [comment]
`wordcloud2.js` is not a JavaScript module. It's a plain old JavaScript file that sets an object on the global. I have no idea how your build script how your build script can understand the file.

I am moving this feature request to [the roadmap document](https://github.com/timdream/wordcloud2.js/blob/263f3abaf785f307f068f6d9a1438c3b94993e9a/CONTRIBUTING.md#play-well-with-modern-build-systems).

**Comment by ghost** [comment]
@smallbitt This is not working for me in Angular 2+ i get the following error:node_modules/@types/wordcloud/index.d.ts' is not a module.
