### ISSUE TITLE
Is there a simple way to prevent word overlaps?

### ISSUE THREAD

**Issue by duncanjbrown** [timdream/wordcloud2.js#116]
This may be a duplicate of #110.

At the moment I am manually tuning `gridSize` and `weightFactor`to spread out my words so they don't overlap. For example, if you were to draw a box around each word, including descenders and ascenders, no part of any other word appears inside that box.

Is this possible to guarantee somehow? If not, is it a hard problem? And if it's not a hard problem, please could you give me some advice on where to start implementing it?

**Comment by timdream** [comment]
This is a dup of #110 and yes it's a non-trivial problem. Thanks for filing.
