### ISSUE TITLE
The words are not 'centered' if the containing div is scaled.

### ISSUE THREAD

**Issue by kongakong** [timdream/wordcloud2.js#118]
Here is the html markup

>                 <h1>Test Wordcloud</h1>
>                 <div class="container">
>                     <div class="wordcloud" style="border:solid 1px blue;width:500px;height:250px;margin:auto"></div>
>                     <div>test</div>
>                 <div>
>                 <input type="button" onclick="draw();" value="gen wordcloud" ></input>
>                 </div>

and the javascript code:

            function draw() {
                    console.log('draw');
                    var wordcloud = $('.wordcloud')[0];
                    var options = {
                        list: [['aaaaaaaa', 50], ['hello', 60]],
                        color: 'black',
                        weightFactor: 2,
                        rotateRatio: 0,
                        rotationSteps: 0
                    };
                    WordCloud(wordcloud, options);
            };

It produces the result as expected:

![image](https://user-images.githubusercontent.com/40389/33744900-d15af9e4-dc07-11e7-89bd-da1a0da942bb.png)

However if I apply a scale transform to the containing div, 

            function draw2() {
                    console.log('draw2');
                    var wordcloud = $('.wordcloud2')[0];
                    $(wordcloud).css('transform', 'scale(1.5)');
                    var options = {
                        list: [['aaaaaaaa', 50], ['hello', 60]],
                        color: 'black',
                        weightFactor: 2,
                        rotateRatio: 0,
                        rotationSteps: 0
                    };
                    WordCloud(wordcloud, options);
            };

The words are put outside the boundary

![image](https://user-images.githubusercontent.com/40389/33744927-fab76c8c-dc07-11e7-848d-4c7baeee49e9.png)

Where in the code likely to produce such result? Is there any workaround?

**Comment by timdream** [comment]
Thanks for filing. I don't think it's possible/efficient to measure the container div transform. It would probably make more sense if you could draw the cloud on a `canvas` or account for the transform yourself.

In the future, a better API might be able to expose detail settings for you to adjust the container dimension manually.

To clean up the issue filed I am moving this feature request to [CONTRIBUTING.md](https://github.com/timdream/wordcloud2.js/blob/cdae623e3d9750d6a18c4727c466969793adfe0d/CONTRIBUTING.md#more-api-features). Thanks for filing!

**Comment by vasilzhigilei** [comment]
```
<div id="surrounding_div" style="width: 100%; height: 300px; text-align: center;">
    <div id="canvas_cloud" class="word_cloud" style="left: 50%; transform: translateX(-50%);"></div>
</div>
```

with the following in the script before options:
```
var div = document.getElementById("surrounding_div");
var canvas = document.getElementById("canvas_cloud");
canvas.style.height = div.getBoundingClientRect().height + 'px';
canvas.style.width  = div.getBoundingClientRect().width + 'px';
```

worked for me to center the div canvas content, with overflow on both sides of the parent div
