### ISSUE TITLE
Flag/event on all words drawn?

### ISSUE THREAD

**Issue by AbhiThakare** [timdream/wordcloud2.js#120]
Hi @timdream 

Thank you very much for this plugin, I loved this plugin and I appreciate all your hard work!

I just want to check is there any event/flag when all words have drawn (population of canvas completed with all words)

I just need to show loader while it populating the canvas and hide loader when it completed so checking for any flag or event.

Regards
Abhi

**Comment by timdream** [comment]
The event you are looking for is `wordcloudstop`. It dispatches as a DOM CustomEvent.

https://github.com/timdream/wordcloud2.js/blob/cdae623e3d9750d6a18c4727c466969793adfe0d/API.md#events
