### ISSUE TITLE
What is the principle rule to pick a best WeightFactor?

### ISSUE THREAD

**Issue by ahbox** [timdream/wordcloud2.js#121]
I have read one of your examples on the demo page.

Here is a part of your code:

`{
  gridSize: Math.round(16 * $('#canvas').width() / 1024),
  weightFactor: function (size) {
    return Math.pow(size, 2.3) * $('#canvas').width() / 1024;
  },
  fontFamily: 'Times, serif',
  color: function (word, weight) {
    return (weight === 12) ? '#f02222' : '#c09292';
  },
  rotateRatio: 0.5,
  rotationSteps: 2,
  backgroundColor: '#ffe0e0'
}`

I noticed some very tricky math as:
`Math.pow(size, 2.3) * $('#canvas').width() / 1024`

Why do we pick the "2.3" and "1024"? I tried it on my container but it seems it's not perfectly working as it shows in the demo. Would you please tell me what kind of numbers should I set? Does it have anything to do with the weights on the list?

I hope to get a "best" number that could make the word cloud fill the most area of the container.

Thanks,

**Comment by timdream** [comment]
It's a mess. `weightFactor` is an ugly workaround for the fact the current impl did not measure the entire cloud on a boundless virtual canvas first. Depend on your font and script you might have better luck on making that number up than mine.

To clean up the issue filed I am moving this feature request to [CONTRIBUTING.md](https://github.com/timdream/wordcloud2.js/blob/cdae623e3d9750d6a18c4727c466969793adfe0d/CONTRIBUTING.md#virtual-canvas-never-miss-a-word-thats-too-big-and-forget-about-weightfactor). Thanks for filing!

**Comment by sergotail** [comment]
It's seems there's no need for virtual canvas. As an option, we can rely on minWeight and maxWeight (read: minFontSize and maxFontSize). These values can be calculated according to canvas size, and, if we need to fit longest word into canvas, words list. Then we can scale all the weights in 2 steps:

1. Apply user-defined scaling function, e.g. `log` or `sqrt` to avoid non-linear wegiths distribution
2. Scale weights something like this (assume there are a methods in some class):
  ```javascript
  scaleValue(value, from, to) {
	  var scale = (to[1] - to[0]) / (from[1] - from[0]);
	  var capped = Math.min(from[1], Math.max(from[0], value)) - from[0];
	  return capped * scale + to[0];
  }
  
  scaledWordsWeights(list) {
	  if (list.length == 0) {
		  return [];
	  }
  
	  let minWeight = null;
	  let maxWeight = null;
  
	  list.forEach(function (item) {
		  if (minWeight === null || item[1] < minWeight) {
			  minWeight = item[1];
		  }
  
		  if (maxWeight === null || item[1] > maxWeight) {
			  maxWeight = item[1];
		  }
	  });
  
	  let minCount = this.calculateMinFontSize();
	  let maxCount = this.calculateMaxFontSize();
  
	  if (minWeight == maxWeight) {
		  return list.map(function(item) {
			  return {
				  [item.word]: ~~maxCount,
			  }
		  });
	  }
	  
	  let from = [minWeight, maxWeight];
	  let to = [minCount, maxCount];
  
	  return list.map(function(item) {
		  return {
			  [item.word]: ~~scaleValue(item.count, from, to),
		  }
	  });
  }
  ```
At least i found this workaround useful in couple with canvas words cloud wrapper, which handles canvas size and hover event.
I'm a newbie at javascript, but maybe this idea might be useful for contributors :)
