### ISSUE TITLE
Callback to set fontWeight based on word weight

### ISSUE THREAD

**Issue by tiagofscoelho** [timdream/wordcloud2.js#123]
Hello :)
Is it possible to add a callback to set fontWeight the same way that we can apply colors?

**Comment by timdream** [comment]
Yes it's possible. Pull request welcome. It's already on the roadmap so I am going to close this issue for now. Thanks!

https://github.com/timdream/wordcloud2.js/blob/gh-pages/CONTRIBUTING.md#more-api-features
