### ISSUE TITLE
Get approximate polar equation for given image

### ISSUE THREAD

**Issue by luke-lee** [timdream/wordcloud2.js#131]
thks for your job!
when i use the wordcoud2.js,I have a problems.the shape i want to use my image,so i use "Get approximate polar equation for given image." page ,but the result is not i want.The screenshot of the problem is as follows,Can you tell me the reason?
![default](https://user-images.githubusercontent.com/40971472/42428267-7e64a824-8365-11e8-8728-95a47fcd99a6.png)

**Comment by timdream** [comment]
There is no way to find a polar equation for your complex shape. Please use a mask. Thanks.

**Comment by luke-lee** [comment]
OK, I see. Thank you.
