### ISSUE TITLE
Using own mask image?

### ISSUE THREAD

**Issue by PeterOeClausen** [timdream/wordcloud2.js#151]
Hey @timdream,
First of all, thank you for making this 😄 

On your website: https://wordcloud2-js.timdream.org under the "Mask image" tab.
It's possible to upload your own image to be used as a mask.
However I can't see a function in the API Docs for this: https://github.com/timdream/wordcloud2.js/blob/gh-pages/API.md

Is this functionality a part of the npm package? Have you forgotten to include it in the API.md? Or is this not something one can use?

Best, Peter.

**Comment by timdream** [comment]
It's a quick app I throw together in the demo page. Not part of the library hence not documented on the API.md. You can look at the demo and create your own.

**Comment by timdream** [comment]
Thanks for asking BTW.

**Comment by PeterOeClausen** [comment]
Thanks! :-)
