### ISSUE TITLE
WordClick doesn't take the current window zoom into effect

### ISSUE THREAD

**Issue by becomingGuru** [timdream/wordcloud2.js#17]
In the file https://github.com/timdream/wordcloud2.js/blob/master/src/wordcloud2.js the function getInfoGridFromMouseEvent ( https://github.com/timdream/wordcloud2.js/blob/2f1e3e6b95e325374e78198c17042df64da2a4b9/src/wordcloud2.js#L340 ) doesn't take window.zoom into account.

**Comment by timdream** [comment]
After hunting for documentation, I realized `zoom` property is not a standardized property (only available on IE and Chrome/Safari) so it will be hard to counter-act it's effect in JavaScript.

I would recommend you talk to the author of reveal.js and have that script to use `transform` property instead.

In the mean time you could recalculate the dimensions in your own `hover` callback, or simply use the new draw-on-a-div feature.

I am closing this as WONTFIX. Please comment if you disagree.
