### ISSUE TITLE
Text box width, which would allow multiline phrases

### ISSUE THREAD

**Issue by lukemunn** [timdream/wordcloud2.js#31]
Is there anyway to limit the width of the text box to a few words or a certain number of pixels? I've gone through the source and can't see how I would do this. I have longer phrases (3-8 words) that I'd love to make into a cloud as multiline 'chunks' of text. Right now they're all single lines which really doesn't work. Tips, tricks appreciated. ;-)

**Comment by timdream** [comment]
@lukemunn Please break them into separate items on the list. You can do `longPhrases.split(' ')` to get an array of words to put into the list.
