### ISSUE TITLE
Problem with Chrome and Win8.1?

### ISSUE THREAD

**Issue by theBear** [timdream/wordcloud2.js#34]
Hello, I use your wonderful wordcloud for http://www.floskelwolke.de

By chance I could see a post on G+ (https://plus.google.com/u/0/+borgdrone/posts/W9f5PQ6gdBv), where the font is incorrect, curiously only with the biggest keyword.

The one, who made the screenshot, told me, he uses Win 8.1 and Chrome.

I have Win7 and tested it also with Google Chrome and couldn't see any probs with the font which is embedded via google fonts.

Is it a known bug? Or why does this appear?

Regards
Sebastian

**Comment by timdream** [comment]
@theBear Sorry for the late reply. The demo page process the input directly on the browser so I am not tracking anything. So what I need here is a set of parameters of the call to tell if it breaks generally or just on Chrome + Windows 8.1. If you still have these please paste them here. Thanks!

**Comment by timdream** [comment]
Closing as WFM. To be reopened if there are more detail.
