### ISSUE TITLE
Problem with window zoom

### ISSUE THREAD

**Issue by steel** [timdream/wordcloud2.js#36]
Steps to reproduce:

Increase Window zoom in Chrome to 110% or higher and load up http://timdream.org/wordcloud2.js/#love

You'll notice that the JS goes into an infinite loop and refuses to render any wordclouds. I've narrowed it down to the grid detection code in `getTextInfo` however I'm not familiar enough with your code to go much further.

**Comment by timdream** [comment]
Fixed by #37.
