### ISSUE TITLE
tooltip on hover

### ISSUE THREAD

**Issue by HedgeShot** [timdream/wordcloud2.js#39]
Hi,

First of all, thank you for this great tool. I am not so advanced in JS and this allowed me to make a great Tag Cloud for my website. 

I have a been working all day on trying to get the jQuery Tooltip to work without success. It is working well on a "test" <div> that never changes in the HTML page with the following JS code:

```
$("#tooltip-2").tooltip({
               	content: "<strong>Hello!</strong>",
               	track:true
});
```
But I can't make it work with the hover function of your tool. I was able to get the basic tooltip from the browser with the correct text inside by changing the title of the "box" div but this obviously gives me enough option to get a decent tooltip (I base my code on your example where you draw a box around the hovered text).

My code looks like that:

```
window.setText = function setText(item, dimension) { 
	if (!dimension) {
		$box.prop('hidden', true); 
		return;
	} 
	$('#wordcloud').attr('title', item[0]); 
}

options.hover = window.setText; 
```

I tried to put something like that a bit everywhere in the code (inside the function, outside, etc..) but nothing works:

```
$("#wordcloud").tooltip({
               	content: "Hi!",
               	track:true
});
```

Any ideas?
Thx

**Comment by timdream** [comment]
Sorry for the late reply. I don't know if you are trying to draw a cloud on a `<canvas>` element or a `<div>`. You should draw on a `<div>` and get the elements drawn and call `$(el).tooltip()` on them.

Please comment if you need further assistance.

**Comment by guiles00** [comment]
Hi tim, i'm trying to draw a cloud on a div element but nothings appear. If a use <canvas> it works perfectly.
What should I do?
this is the div 
   `<div id="html-canvas" class="canvas" width="1170" height="760">
</div>`
Thanks!
