### ISSUE TITLE
please tag a release

### ISSUE THREAD

**Issue by Aaike** [timdream/wordcloud2.js#41]
Hi could you please tag a release version for this library ? it would help with my package manager.

**Comment by timdream** [comment]
@Aaike Which package manager you are using? Can you specify a hash instead?

I am happy to tag it for you but I don't know the version scheme I should be using.

**Comment by Aaike** [comment]
Hi i'm using jspm, it uses normal semver ranges.

**Comment by daithi-coombes** [comment]
I use `npm` for managing my packages and the lack of the version in `package.json` file is preventing this, shoudl be an easy fix

**Comment by daithi-coombes** [comment]
I've create a pull for this..
https://github.com/timdream/wordcloud2.js/pull/43

**Comment by timdream** [comment]
The library has been published on npm and versions are all tagged. Thanks.
