### ISSUE TITLE
Shape generator not working

### ISSUE THREAD

**Issue by antonioj1015** [timdream/wordcloud2.js#42]
I uploaded a black and white image but as soon as I loaded it appears a black and green image.  Isn't there a more simple way to create a custom shape? Or am I doing something wrong?

I'll be using the Silhouette of a men and a women....this is an image I tried it out with (Not the one I'll be using, just for testing)...
![sin titulo](https://cloud.githubusercontent.com/assets/5767462/7237922/8031d7e4-e764-11e4-9dab-a9a455d11411.png)
this is what it shows:
![image](https://cloud.githubusercontent.com/assets/5767462/7237939/a01013d2-e764-11e4-95cb-f683c496e008.png)

**Comment by lzxue** [comment]
I have this problem too !

the erro：
![image](https://cloud.githubusercontent.com/assets/4366658/7361633/8cc8780c-ed8e-11e4-82eb-5f3189f85b2d.png)

**Comment by timdream** [comment]
I've just pushed ae89662 to fix this issue. The original code was untest code targeted my own image, which is not exactly black and white. 

Please note the text can only expand along the green lines drawn, so if your shape is too irregular the cloud might not be occupy these edges.

**Comment by lzxue** [comment]
thx,it's ok!
