### ISSUE TITLE
Scale of word value?

### ISSUE THREAD

**Issue by jiacheliu3** [timdream/wordcloud2.js#50]
Hi! 
May I know what how the range of value is mapped to the size of word drawn please? I put the value in a scale of [50,100] and [500,1000] but they ended up shown the size of ants....
I didn't use weight factors or minimal font size etc in the parameters, just passed in a list with all value scaled. It there a suggested value range with all other parameters by default? Or shall I just go ahead and increase the weightFactor etc?
Thanks in advance!

**Comment by timdream** [comment]
Please increase the `weightFactor` instead.

**Comment by jiacheliu3** [comment]
Works pretty well :) Thanks.
