### ISSUE TITLE
WordCloud not showing if all words have same frequency

### ISSUE THREAD

**Issue by RaphBlanchet** [timdream/wordcloud2.js#51]
Hi,

I've done some testing with your library, and I seems to have stumbled on a bug. If all the words of the list have the same frequency, then the cloud will not show up and a javascript exception will be thrown : 

`TypeError: Argument 3 of CanvasRenderingContext2D.getImageData is not a finite floating-point value.`

i.e : [['Internet', 3], ['Google', 3], ['Web', 3]]

Making a WordCloud with these frequencies will not work. (Unless I'm doing something wrong? My WordCloud usually appears, but not with these values)

**Comment by timdream** [comment]
Thanks for the report. The frequency is not likely the cause -- the demo page do that exactly.

Could you paste the entire function call here and also the dimension of the canvas? I can only fix this if I could reproduce it. Thanks.

**Comment by RaphBlanchet** [comment]
Really sorry, just found out that the bug was caused by a calculation we were doing on the Weight Factor, which resulted in a division by 0. All my apologies, everything works fine now that we found that!
