### ISSUE TITLE
Examples on non-radial shapes?

### ISSUE THREAD

**Issue by av01d** [timdream/wordcloud2.js#52]
Hi Tim,

Is it possible to have non-radial shapes for wordclouds? Your shape-generator.html is a nice tool for generating new wordcloud shapes, but the process is based on drawing lines from one central point.
For example: I'd like to have a shape of a world map. Does wordcloud2.js support such 'arbitrary' shapes? If so, how do I generate the coordinates for the "theta" function?
Do you maybe have some examples?

**Comment by timdream** [comment]
You would have to do it with a picture mask by draw the "ocean" on the <canvas> first and set the "land" color to WordCloud as the color that can be used to place text.

**Comment by av01d** [comment]
Thanks for you reply, but I'm not sure I understand yet. Until now, I always use shape-generator.html to generate cloud shapes. Does the process you describe use shape-generator.html at all? Or is it something I need to do in wordcloud2.js? Where do I set the "land" color?
An example might be useful? Thanks again.

**Comment by timdream** [comment]
1. Paste your world image into the canvas. (`ctx.drawImage()` and whatnot)
2. Ask WordCloud to draw on that canvas with `clearCanvas` to `false` and `backgroundColor` of the color to be drawn words over (I assume that's the color of the continents for an image of a world map).
 
https://github.com/timdream/wordcloud2.js/blob/master/API.md#presentation

You don't need `shape-generator.html`.

Please consider contributing by submit a pull request to show your work as a new demo once you figure out how to do it :)

**Comment by noahjcz** [comment]
I'm trying to follow this, but when I set clearCanvas: false, the word cloud doesn't work at all (nothing draws).  Would it be possible to post a short code example?  Thanks!
