### ISSUE TITLE
Click setting

### ISSUE THREAD

**Issue by akhilr** [timdream/wordcloud2.js#54]
Hi, 

First off, thanks for making this excellent plugin!

I had a question, is there any way to call each word on click.

Thank you in advance.

**Comment by timdream** [comment]
If you draw a cloud on a `<canvas>`, the function in `click` option will be called when the user click on a specific word.

https://github.com/timdream/wordcloud2.js/blob/master/API.md#interactive

For a HTML cloud, you could bind an event listener on the container and inspect `evt.target` to find out the current `<span>` the user it click on.

**Comment by akhilr** [comment]
Thanks for your response!
Apologies, maybe I didn't explain myself well enough.
I'm trying to make each individual span appear on a particular event. For example, to generate each new word when the user clicks.

**Comment by timdream** [comment]
You can achieve that by calling `WordCloud()` again, asking it to draw a new word upon click, without clean up the current canvas.

**Comment by akhilr** [comment]
How would I stop the loop after it draws each word, though?

**Comment by timdream** [comment]
Only draw a word one at a time :) The trick here is not to wipe the canvas in the subsequent draw.

**Comment by akhilr** [comment]
My main issue is that the list contents are dynamic. Length of the list is fixed though. So what I need is that every time a new word is added I need to draw it in the WordCloud.

After placing this new word, it should pause and wait for the new word. Once all the "unique" words in the list are received, then I can let WordCloud go about its business. 

So basically I need to find a way to pause Wordcloud, after it outputs each span, and wait for me to unpause it.
