### ISSUE TITLE
wait: 0 should probably freeze the browser instead of use setImmidiate

### ISSUE THREAD

**Issue by ashokduddukuri** [timdream/wordcloud2.js#55]
How to display without any animation? is there any flag for it?

**Comment by timdream** [comment]
What do you mean by animations? There isn't any animations built-in..

**Comment by ashokduddukuri** [comment]
In this [exampe](http://timdream.org/wordcloud2.js/#love), all the data is not shown instantaneously.It takes some time to display complete tag cloud.

**Comment by timdream** [comment]
That's not animation, that's because each tick is quite demanding to the browser (even on Desktop) so if I don't do things separately in a `setTimeout()` loop your browser will freeze.

You could change the `wait` property to `0` instead.

https://github.com/timdream/wordcloud2.js/blob/master/API.md#timing

**Comment by ashokduddukuri** [comment]
Thanks for the explanation.I am converting tag cloud to pdf using wkhtmltopdf but it seems complete data is not shown because of delay in rendering complete tag cloud. Even setting to wait:0 it dosne't seems to rendering instantaneously. I understood problem with rendering every thing at once, just let me know if there is a way to do it else you can close this. Thanks

**Comment by timdream** [comment]
That's very easy. Just have your script injected into your page and listen to `wordcloudstop` event dispatched from here:

https://github.com/timdream/wordcloud2.js/blob/master/src/wordcloud2.js#L1072

That's the definitive timing for you to start pull the rendered result.

**Comment by timdream** [comment]
@ashokduddukuri I am closing this issue as solved per suggestion above. Feel free comment if there is any other suggestions.
