### ISSUE TITLE
word cloud flash and disappear on IOS 8.3

### ISSUE THREAD

**Issue by rayeaster** [timdream/wordcloud2.js#57]
I have a word cloud, it first show and then disappear...could any one shed some light here?

**Comment by rayeaster** [comment]
my container is a height-given <canvas> and my word value is Chinese with weight between [4,8] and following options:

var option = {
        		list:list,
        		gridSize: Math.round(16 * $('#memCloudCanvas').width() / 1024),
        		weightFactor: function (size) {
        		  return Math.pow(size, 2.3) * $('#memCloudCanvas').width() / 1024;
        		},
        		shape:'pentagon',
        		minRotation: 1.58,
        		maxRotation: 1.58,
        		rotateRatio: 0,
        		color: 'random-dark',
        	    fontFamily: "'Microsoft YaHei', 'WenQuanYi Micro Hei', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Hiragino Sans GB', Helvetica, sans-serif",
//        		backgroundColor: '#fff'	
        	};

**Comment by rayeaster** [comment]
it seems it is due to the "fontFamily" setting

**Comment by timdream** [comment]
Are you drawing a cloud on a `<div>` or a `<canvas>`...?

Anyhow, this is probably a bug in the browser.
