### ISSUE TITLE
Manual for Shape Generator?

### ISSUE THREAD

**Issue by theBear** [timdream/wordcloud2.js#59]
Hi,

is there any documentation for the shape generator? 

I have something like this:

```
function(theta) {
  var max = 1901;
  var leng = [1877,1880,1881, ...];

  return leng[(theta / (2 * Math.PI)) * leng.length | 0] / max;
}
```

How to _install_ this to wordcloud2.js?

**Comment by timdream** [comment]
The shape function can be used in the `shape` option.

https://github.com/timdream/wordcloud2.js/blob/master/API.md#shape

If that's not clear enough feel free to submit a pull request and document it there. Thanks!
