### ISSUE TITLE
Hover - Uncaught TypeError

### ISSUE THREAD

**Issue by TommasoBelluzzo** [timdream/wordcloud2.js#69]
Whenever I hover an empty area of a wordcloud canvas, normally on the left side and very close to the border, I keep on receiving this error:

   Uncaught TypeError: Cannot read property '[ANY NUMBER]' of undefined
     getInfoGridFromMouseTouchEvent @ wordcloud2.min.js
     wordcloudhover @ wordcloud2.min.js

**Comment by timdream** [comment]
This is a bug due to the fact the grid does not cover the entire canvas. `getInfoGridFromMouseTouchEvent` should not throw but return a undefined `info` struct instead.

It's harmless though as we did not mistakenly trigger `hover` callback.

**Comment by AbhiThakare** [comment]
Hi, 

Is there any workaround for this?

**Comment by AbhiThakare** [comment]
Hi,

I am still facing this issue on hover and keep receiving many times.

Thanks 
Abhi
