### ISSUE TITLE
Is it possible to use the function to fontFamily option?

### ISSUE THREAD

**Issue by unasd** [timdream/wordcloud2.js#76]
I want to dynamically change fontFamily based on the word .

like below

```
fontFamily: function(word){
    var returnFont;
    if( word == 'category1'  ) returnFont = 'Gothic';
    else if( word == 'category2' ) returnFont = 'serif';
    return returnFont;
},
```

I tried it already and it seems not working.
Is there anyway to do?

ps. thx for your work!

**Comment by timdream** [comment]
Not possible, but certainly can be implemented.

**Comment by unasd** [comment]
I solved the problem through this article. [issue24](https://github.com/timdream/wordcloud2.js/issues/24)
