### ISSUE TITLE
How to attach data attributes to the rendered words

### ISSUE THREAD

**Issue by rohitkhatri** [timdream/wordcloud2.js#77]
I'm thinking of some callback while rendering, I can get the span and should be able to attach some data attributes so I can access them when a word is clicked on.

Thanks

**Comment by timdream** [comment]
That's a good idea. With all these issues I think I should eventually come up with a plug-in framework (it's no possible to implement all use cases into the one and only core code).

In the mean time you could listen to `wordclouddrawn` custom event and attach data attribute to the last, newly created `<span>` in the containing element.

**Comment by rohitkhatri** [comment]
Thanks for the help, I will try this out now, and update you If It works for me.

**Comment by rohitkhatri** [comment]
Can you give me an example using the `wordcolulddrawn` event?

**Comment by enchaowu** [comment]
if the outline is administrative divisions, how to make it work well ?

**Comment by timdream** [comment]
> Can you give me an example using the wordcolulddrawn event?

https://github.com/timdream/wordcloud2.js/blob/08149c110250741ac7e4139629d3053756fbeaf4/src/wordcloud2.js#L1134

It's a custom DOM event, so you should be able to subscribe it with `addEventListener` or `jQuery.on`.

> if the outline is administrative divisions, how to make it work well ?

I don't really understand what this question means...

**Comment by timdream** [comment]
I assume this issue is fixed. Please comment if it's not.
