### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by ITGuyJosh** [timdream/wordcloud2.js#78]
Hello, I am attempting to combine the WordFreq & WordCloud2 js libraries to create a basic wordcloud from some text. I am able to return the words correctly in the [['one', 1], ['two', 2]] format, but I keep on getting TypeErrors when I apply the array to wordcloud2.js. I've attached screenshots of my error and code. Any help would be appreciated!

<img width="632" alt="screen shot 2016-10-21 at 22 52 44" src="https://cloud.githubusercontent.com/assets/10251981/19612954/81b7d594-97e1-11e6-8c9b-7e21957f6bf7.png">
<img width="601" alt="screen shot 2016-10-21 at 22 52 12" src="https://cloud.githubusercontent.com/assets/10251981/19612963/886ff4fc-97e1-11e6-993a-d65bd8cd2115.png">

**Comment by timdream** [comment]
That simply means `document.getElementById("#visual-source")` is `null`. Your HTML should have something like `<div id="visual-source">`.

Also, You don't need to `JSON.stringify` the list.

**Comment by ITGuyJosh** [comment]
Thank you for your quick reply tim, but I already checked that and that isn't it. I'm not that bad, I hope, that I forgot a basic html ID thankfully. I think it may be due to the order which the DOM is loaded? But even when I make the script the last thing to execute, it doesn't seem to work, hmmm.

<img width="313" alt="screen shot 2016-10-22 at 06 54 47" src="https://cloud.githubusercontent.com/assets/10251981/19617271/7ef809ee-9824-11e6-857b-e52b450b695d.png">

**Comment by timdream** [comment]
Maybe a `console.log('>>>', document.getElementById("#visual-source");` right before the line you call `WordCloud` can help you make sure there isn't any execution order issue?

**Comment by ivan2941** [comment]
When you use getElementById method there's no need to include the #, it's redundant. Just pass it a string with the name you're looking for, like this:
_**document.getElementById('visual-source');**_
So jquery would search for an element like this: _`<div id="visual-source"></div>`_
Otherwise it would be searching for an element like this: _`<div id="#visual-core"></div>`_

;)

**Comment by cuunonhaitac** [comment]
I think I figure out the problems. We just put the variable in document.addEventListener likes this:
<script>
	document.addEventListener('DOMContentLoaded', function() {
	var typed = new Typed("#typed", {
	    stringsElement:'#typed-strings',
	    typeSpeed: 30,
  	});
});
</script>

**Comment by sasithahtl** [comment]
> That simply means `document.getElementById("#visual-source")` is `null`. Your HTML should have something like `<div id="visual-source">`.
> 
> Also, You don't need to `JSON.stringify` the list.

thanks. saved the day.

**Comment by mihirk98** [comment]
Put your script tag at the end of your body or wait until DOM loads to execute your script. Your script is running before your DOM is rendered.
