### ISSUE TITLE
Blurred output

### ISSUE THREAD

**Issue by themerius** [timdream/wordcloud2.js#81]
WordCloud produces in my canvas only blurred images (resolution of 300x150 pixel, just resized larger). Here is a snippet of my code experiment:

    <canvas style="width: 100%; height: auto;" id="wc2"></canvas>

    <script>
    var opts = {
      "gridSize": 1,
      "list": [['Mini Mental State Examination', 2],['nervous system disease', 2],['Neuropsychological Test Battery', 2],['Falls', 10],['relative risk', 2],['Study Logistics', 2],['CSF', 4],['Hypertension', 2],['Body weight', 2],['Clinical Trial Study', 2],['Control', 2],['Confidence interval', 2],['Data Management', 22],['Alzheimer\'s disease', 2],['Both', 12],['Informed consent', 2],['myocardial infarction', 18],['Sleep disturbance test', 24],['Disability', 2],['Study Objective', 8],['Laboratory', 2],['Completed', 8],['Interventional study design', 4],['Design and Analysis plans', 6],['Heart Failure', 4],['cognitive decline', 2],['Protocol Representation Sub Domain', 2],['Urine', 2],['Cognitive Readouts', 6],['Memory and learning', 2],['Standard Deviation', 2],['Quality of life', 2],['Sleep Initiation and Maintenance Disorders', 18],['Plaque, Amyloid', 40],['depressive symptoms', 2],['Sleep Deprivation', 4],['Cross sectional study design', 2],['Pet scan', 30],['Clinical Dementia Rating Scale sum of boxes', 4],['Prevention', 4],['cancer', 2],['Scale for Depression', 2],['Bronchitis, Chronic', 2],['Prospective', 2],['melancholia', 2],['Diagnostic', 8],['Biological Specimen', 6],['cognitive subscale', 2],['Blood', 2],['Disease', 8],['Mobility Limitation', 2],['mobility', 2],['sleep apnea', 10],['Change from baseline', 2],['Dementia', 18],['emphysema', 2],['Female', 4],['Lung Diseases', 6],['Chronic Pain', 2],['Alzheimers disease', 46],['APOE', 8],['CSF Alpha beta 42 level', 54],['Historical', 6],['Neuroimaging Structural', 6],['Outcome measured after measurement of predictors', 6],['Cohort study design', 2],['Status', 2],['Hazard ratio', 2]]
    }

    WordCloud(document.getElementById('wc2'), opts );
    </script>

I've missed something in my code to get high-res word clouds?

**Comment by timdream** [comment]
You would need to set the pixel `width` and `height` attributes of the canvas element, not just sizing it with CSS, for example: `<canvas width="1024" height="768" style="width: 100%; height: auto;" id="wc2"></canvas>`

Please reply if you have further problems.

**Comment by themerius** [comment]
Thank you. That helped me!

Maybe this should made more prominent in the user documentation?
