### ISSUE TITLE
Using 'drawOutOfBound' property results in distorted cloud

### ISSUE THREAD

**Issue by shlomiLan** [timdream/wordcloud2.js#83]
I have used the first example in the [demo](https://timdream.org/wordcloud2.js/#) page with the following configuration:
`
{
weightFactor: function (size) {
    return Math.pow(size, 2.3) * $('#canvas').width() / 1024;
  },
rotateRatio: 0,
shuffle: false,
maskGapWidth: 0,
minSize: 9,
drawOutOfBound: true
}
`
and with `Height=300px`.

In this case, lots of words are not displayed, if I remove the `drawOutOfBound: true` configuration I see much more words, but I have to use this property because I want to sure that all the words are displayed. 
Also If I use the `drawOutOfBound: true` configuration and remove the `overflow: hidden;` setting from the container div I see that lots of words are been displayed one over the other on the bottom of the wordcloud, you can see an example in the attached file.
![image](https://cloud.githubusercontent.com/assets/13360912/21672128/df9a3c9c-d328-11e6-8de7-fb2cc806852d.png)

**Comment by timdream** [comment]
@shlomiLan Thanks for filing. What's the `width` of the canvas?

**Comment by shlomiLan** [comment]
I haven't changed it so `width="1170"`

**Comment by timdream** [comment]
@shlomiLan From the font I assume it's on Windows?

**Comment by timdream** [comment]
@shlomiLan Could you set `drawMask: true` and paste the screenshot again? Thanks. I am pretty sure this is a bug...

**Comment by shlomiLan** [comment]
Yes, I'm using Windows 10 and Chrome browser.
I have added `drawMask: true`, but I don't see any change.
![image](https://cloud.githubusercontent.com/assets/13360912/21672902/23610528-d32e-11e6-8abc-8700765c9959.png)

**Comment by timdream** [comment]
@shlomiLan Can you give me a screenshot of the "Canvas" canvas? Just click on the button on the right of the [Run] button.

**Comment by shlomiLan** [comment]
![image](https://cloud.githubusercontent.com/assets/13360912/21673068/4023a106-d32f-11e6-8e6e-d64fc1116f5b.png)

**Comment by timdream** [comment]
@shlomiLan Thanks. I don't see anything wrong with this screenshot, no?

So what happens here is that, when you set `outOfBound: true`, WordCloud will draw words even if it's outside of the canvas, *and* will not record the occupancy information of that area (it will forever remain as "available to place more words".

This would not be a problem for a `<canvas>` canvas, because there are no pixels outside of the canvas anyway. However, since you removed `overflow: hidden`from the HTML canvas (the `<div>`), you revealed the words that are supposed to be cut off.

I should have read your comments earlier instead of just looking at the image. This issue is invalid as WordCloud work as intended. Thank you again for filing the issue!

**Comment by shlomiLan** [comment]
The last image that I sent you it's without `overflow: hidden`. So I didn't really understand how using a canvas solves the issue?

**Comment by shlomiLan** [comment]
Sorry, what I meant to write is that in the last example that I sent you I **DID NOT** removed the `overflow: hidden` proprty and I use a canvase, but still there were some missing words.

**Comment by timdream** [comment]
@shlomiLan `outOfBound: true` is not meant to make sure every word appears; if you canvas is full words will be "pushed out" regardless. What it does help is the cases where the word itself is larger than the canvas **and** the canvas is still empty.

**Comment by shlomiLan** [comment]
I understand now, so what should be the best configuration for displaying the maximum number of words? decreasing the `gridSize` value?

**Comment by timdream** [comment]
`weightFactor` should be the one.
