### ISSUE TITLE
Type of minFontSize ( local and global )

### ISSUE THREAD

**Issue by Marlysson** [timdream/wordcloud2.js#85]
The type expected in minSize of local object and Wordcloud.minFontSize ( global object ) , it integer ( 20 ) or string ( '20px' ) ?

**Comment by timdream** [comment]
It's integer in CSS pixels: https://github.com/timdream/wordcloud2.js/blob/976883a0b714883d08ca9ef27b57b6984eca746a/src/wordcloud2.js#L118-L145

**Comment by Marlysson** [comment]
Great!! Thank you.
