### ISSUE TITLE
Webkit and Blink render different wordclouds

### ISSUE THREAD

**Issue by namirsab** [timdream/wordcloud2.js#87]
### Observed
Webkit and Blink are placing the words in different places with the same attributes

### Expected
is browser agnostic

### Reproduce by
1. Create a wordcloud.
2. Render it in different browsers

**Comment by timdream** [comment]
Thanks for filing. Did you turn off a the randomness properties?

**Comment by namirsab** [comment]
@timdream yes I turned off every randomness properties. What I see is that in chrome and safari the wordclouds look properly (but some words are set in another place), and in firefox (in Linux) words overlap each other.

**Comment by timdream** [comment]
Do you have a test case for me to run?

**Comment by namirsab** [comment]
mmm unfortunately not, but i can build it.
I'll try to post it during this week okey?

**Comment by timdream** [comment]
If this is reproducible with options on the demo page (https://timdream.org/wordcloud2.js/), tell me the options and I can try to reproduce it. No need to build a page in that case. It's only happen on Firefox on Linux? Do you have any privacy/anti-fingerpointing thingy turned on? Thanks.

**Comment by namirsab** [comment]
@timdream could you explain what do you mean? like an adblock or something?

**Comment by namirsab** [comment]
Okey, you can reproduce it with this settings:
```js
{
  gridSize: Math.round(16 * $('#canvas').width() / 1024),
  weightFactor: function (size) {
    return Math.pow(size, 2.3) * $('#canvas').width() / 1024;
  },
  fontFamily: 'Times, serif',
  color: function (word, weight) {
    return (weight === 12) ? '#f02222' : '#c09292';
  },
  rotateRatio: 0,
  rotationSteps: 0,
  backgroundColor: '#ffe0e0',
  shuffle: false
}
```
My firefox version is 52.0 in Linux Mint 18
Chrome is latest stable for Linux

#### Chrome
![image](https://cloud.githubusercontent.com/assets/6980777/24140809/a1a240ea-0e21-11e7-88d5-68dd52ec848d.png)

#### Firefox
![image](https://cloud.githubusercontent.com/assets/6980777/24140836/b9658a70-0e21-11e7-9c6f-bcfbc30200c8.png)

**Comment by timdream** [comment]
I see what you are saying now. It's expected that different browser renders the cloud differently. Browsers comes with different default font (in this case, `Times` maps to different font on Linux), and use different font rendering technologies. It's unlikely, if not impossible, to make different browser render the cloud with pixel-identical result.

I am closing this as a non-issue. Will re-open if I don't understand your problem correctly.

**Comment by namirsab** [comment]
@timdream I can set up an example using the same font and everything if you like. Should they render the same way in that case?

**Comment by timdream** [comment]
@namirsab No. You can't replace the font rendering engine (unless you draw/raster the font yourself with like [opentype.js](https://github.com/nodebox/opentype.js)).
