### ISSUE TITLE
How do I mix a picture in a word cloud?

### ISSUE THREAD

**Issue by cqgsm** [timdream/wordcloud2.js#91]

**Comment by timdream** [comment]
You would need to use Canvas Context2D API to draw the image on the canvas first.

**Comment by cqgsm** [comment]
This picture can not be the background, for example, a QRCode in the middle of the canvas, and then other words around it to generate the word cloud

**Comment by timdream** [comment]
Yes you can do that with my comments above, just don't set the `clearCanvas` to true.
