### ISSUE TITLE
The code won't work if compress the HTML code

### ISSUE THREAD

**Issue by andy-cywang** [timdream/wordcloud2.js#92]
Hi, I know it sounds unnecessary to compress the code before running, but for some special reasons my processor in another software will compress the html code into one line before running it. In this case, the code won't work and throw an error saying the object WordCloud is an "Unexpected identifier".

Thanks in advance if you could help me to look at the file I attached. I get no issues to run the code without  compressing, but get the error mentioned above by using compressed version (line 817). Is there any reason on why this happening?

[testing code.txt](https://github.com/timdream/wordcloud2.js/files/946702/testing.code.txt)

**Comment by timdream** [comment]
I really can't help you with that. Sorry. Please consult the author of your compresser/optimizer/transplier and try to ask them to fix this. I am fine if it's easier to fix here I can take a pull request but I really can't debug an unknown compresser out there.

**Comment by andy-cywang** [comment]
Hi,

Thanks for reply my request. Actually any compresser can cause this issue.
Actually, the code at line 817 is not from my software, it was compressed
by this site: http://www.textfixer.com/html/compress-html-compression.php

Basically, if we put the code just in one line, then it won't work as the
WordCloud cannot be recognized.

Thanks!

2017-04-21 18:15 GMT+08:00 Timothy Guan-tin Chien <notifications@github.com>
:
