### ISSUE TITLE
Blurry output

### ISSUE THREAD

**Issue by selecta-ufuk** [timdream/wordcloud2.js#97]
hi @all,

can some one tell me why i always get a blurry font out?
![image](https://cloud.githubusercontent.com/assets/28607690/26276652/937c27a4-3d7b-11e7-8db2-acab795b55aa.png)

in html :
  canvas id="word_cloud" class="word_cloud" height="190" width="380"></canvas

in js:
    var options =
              {
                list : cloud,
              rotateRatio: 0,
            gridSize: 5,
              };

            WordCloud.minFontSize = "15px";
           WordCloud(document.getElementById('word_cloud'), options); 

thx

**Comment by timdream** [comment]
What's the actual CSS size of your canvas and device pixel ratio? The height and width only set the pixel size of the canvas.

**Comment by selecta-ufuk** [comment]
for canvas in css only use position.
same prob:
[http://stackoverflow.com/questions/28983250/word-cloud-getting-blurry](url)

`#canvas {
    top: 10px;
    position: relative;
    z-index: 0;
}`

**Comment by timdream** [comment]
That's odd. Could you use the DevTools inspector to see the *actual* CSS side of the canvas on the page? Also, what's the device pixel ratio (can be accessed with `window.devicePixelRatio`). Thanks.

**Comment by selecta-ufuk** [comment]
css out of object :
`color:
rgb(20, 20, 20)
;
display:
inline
;
font-family:
Dosis, sans-serif
;
font-size:
12px
;
height:
190px
;
position:
relative
;
text-align:
center
;
top:
10px
;
width:
380px
;
z-index:
0
;`

from console:
window.devicePixelRatio
2

**Comment by timdream** [comment]
OK. So it looks like you are on a hi-dpi device. Except on Safari, `<canvas>` are always measured in CSS pixels. Given that one CSS pixel equals 4 device pixels on your device, you'll need to set canvas width and height to 2x of the CSS pixel. Like this:

`<canvas width="760" height="380" style="width: 380px; height: 190px">`

I am going to close this one as this is unrelated to WordCloud. Here is [an article](https://www.html5rocks.com/en/tutorials/canvas/hidpi/) that might help you further. Thanks.

**Comment by selecta-ufuk** [comment]
works!!!!
thanks
