### ISSUE TITLE
demo render ???? for some word on safari

### ISSUE THREAD

**Issue by cedricwalter** [timdream/wordcloud2.js#98]
reload the page https://timdream.org/wordcloud2.js/#les-miz
Sometimes the cloud is not properly displayed only in safari ios/mac, some words are replaced randomly with ?????????? but not all

Can you help?
Thanks & regards

**Comment by timdream** [comment]
@cedricwalter Thanks for filing. This should be a bug in Safari — apparently, it draws question marks instead of the fallback font (`Times`) when the Web font (`Average`) is being loaded.

I wonder if this should be filed on WebKit.
