### ISSUE TITLE
automatic calculation of sizes to fill up space

### ISSUE THREAD

**Issue by jabadia** [timdream/wordcloud2.js#99]
Is there a way to have WordCloud calculate automatically the weightFactor so that the words fill all the available space?

Thanks

**Comment by timdream** [comment]
No :'( Because we don't know the "emptiness" of each of the glyphs without actually reading the pixels.

The alternative would simply make the cloud scale at the very end to fit the space, but that takes a full write. I believe there is already opened issue talked about this so closing.
